stages:
  prepare_raw_data:
    cmd: python3 src/unzip.py
    deps:
      - src/unzip.py
      - data/raw/raw_zipped.zip
    outs:
      - data/raw/cell_images

  eda:
    cmd: python3 src/eda.py
    deps:
      - src/eda.py
      - data/raw/cell_images
    params:
      - data
    metrics:
      - reports/metrics/eda_metrics.json

  preprocess:
    cmd: python3 src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/cell_images
    params:
      - data
      - split
    outs:
      - data/processed/split

  resize:
    cmd: python3 src/resize.py
    deps:
      - src/resize.py
      - data/processed/split
    params:
      - data
      - preprocess
    outs:
      - data/processed/resized


      
  train:
    cmd: python3 src/train.py
    deps:
      - src/train.py
      - src/models.py
      - data/processed/resized
    params:
      - train
      - model
    outs:
      - models
    metrics:
      - reports/metrics/train_metrics.json
  evaluate:
    cmd: python3 src/evaluate.py
    deps:
      - src/evaluate.py
      - src/models.py
      - models
      - data/processed/resized
    params:
      - train
      - data
    metrics:
      - reports/metrics/eval_metrics.json

    plots:
      # overall metrics (accuracy, f1, etc.)
      - reports/plots/eval_metrics_plots.json:
          template: bar_horizontal
          x: value
          y: metric

      # confusion matrix
      - reports/plots/confusion_matrix.csv:
          template: confusion_normalized
          x: predicted
          y: actual

      # metric scatter 
      - reports/plots/scatter_metrics.json:
          template: scatter
          x: accuracy
          y: f1

      # per-class F1 
      - reports/plots/per_class_f1.json:
          template: bar_horizontal
          x: f1_score
          y: class
